enabled = "yes"

[settings]
url_prefix = "/users"
#subdomain = ""
#url_defaults = {}
#static_folder = "static"
template_folder = "templates"
#static_url_path = "/users/static"

#[session]
#users_session = "yes"

