enabled = "yes"

[settings]
url_prefix = "/"
subdomain = ""
url_defaults = {}
static_folder = "static"
template_folder = "templates"
static_url_path = "/comming_soon/static"

[session]
comming_soon_session = "yes"

