services:
  web:
    container_name: flask_planet_org
    image: cheesecake87/flask-planet.org:b2
    ports:
      - "4002:5000"
    volumes:
      - flask_planet_db:/flask/app/db
    environment:
      - CONFIG_SECRET_KEY=SET_ME_TO_SECRET
#     UNCOMMENT BELOW TO IP LOCK THE ADMIN LOGIN
#      - ALLOWED_IPS=127.0.0.1,127.0.0.2

volumes:
  flask_planet_db: