enabled = "yes"

[settings]
url_prefix = "/system"
subdomain = ""
url_defaults = {}
static_folder = "static"
template_folder = "templates"
static_url_path = "/system/static"

[session]
system_session = "yes"

