enabled = "yes"

[settings]
url_prefix = "/resources"
#subdomain = ""
#url_defaults = {}
#static_folder = "static"
template_folder = "templates"
#static_url_path = "/pages/static"

#[session]
#pages_session = "yes"
