[flask]
APP_NAME = "com-flask-planet"
BUILD = "1"
SECRET_KEY = "iWZwwYpexWZQPysbdVJbWKgNYBCJfzuekeiU"
SESSION_COOKIE_NAME = "uXiSiZLk"
DEBUG = false
TESTING = false
SESSION_TIME = 480
ERROR_404_HELP = true
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXPLAIN_TEMPLATE_LOADING = false

[database.main]
enabled = true
type = "sqlite"
database_name = "database"
location = "db"
port = ""
username = "user"
password = "password"


[SESSION]
logged_in = false
user_id = 0
username = ""