[flask]
APP_NAME = "app"
VERSION = "0.0.1"
SECRET_KEY = "<CONFIG_SECRET_KEY>"
DEBUG = true
TESTING = false
SESSION_TIME = 480
ERROR_404_HELP = true
SQLALCHEMY_TRACK_MODIFICATIONS = false
EXPLAIN_TEMPLATE_LOADING = false

[database.main]
enabled = true
type = "sqlite"
database_name = "database"
location = "db"
port = ""
username = "user"
password = "password"


[SESSION]
logged_in = false
user_id = 0
username = ""