enabled = "yes"

[settings]
url_prefix = "/dev"
#subdomain = ""
#url_defaults = {}
#static_folder = "static"
template_folder = "templates"
#static_url_path = "/dev/static"

#[session]
#dev_session = "yes"
