enabled = "yes"

[settings]
url_prefix = "/news"
subdomain = ""
url_defaults = {}
static_folder = "static"
template_folder = "templates"
static_url_path = "/streams/static"

[session]
streams_session = "yes"

